#! /bin/sh

userresources="$HOME/.config/X11/Xresources"
usermodmap="$HOME/.config/X11/Xmodmap"
xprofile="$HOME/.config/X11/xprofile"

[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$xprofile" ] && . "$xprofile"

nvidia-settings --load-config-only
# start wm
# exec bspwm
# exec xmonad
exec dwm
