#!/bin/sh
# Put some color in life
alias \
	ls="exa --color=always --group-directories-first" \
	la="exa -al --color=always --group-directories-first" \
	ll="exa -l --color=always --group-directories-first" \
	lt="exa -aT --color=always --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
    cp='cp -iv' \
    rm='rm -iv' \
    mv='mv -iv' \
    mkdir='mkdir -pv' \
    more='less' \
    vi='vim' \
    df='df -h' \
    free='free -m' \
    wget='wget -c' \

# I am Lazy so what
alias \
    e='$EDITOR' \
    v='$EDITOR' \
    pi='sudo pacman -Syu' \
    yi='yay -Syu' \
    prs='sudo pacman -Rs' \
    yrs='yay -Rs' \
    pq='sudo pacman -Ss' \
    yq='yay -Ss' \
    prm='sudo pacman -R' \
    yrm='yay -R' \
    yc='yay -Sc' \
    pkgs='pacman -Q | less'

# Ease of life
alias \
    aliasrc='$EDITOR $HOME/.config/aliasrc' \
    vinit='$EDITOR $HOME/.config/nvim/init.vim' \
    rebash='$EDITOR $HOME/.bashrc' \
    zshrc='$EDITOR $ZDOTDIR/.zshrc' \
    cfg='git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME' \

# Not safe
alias \
    nuke='rm -rf' \
    sdn='poweroff' \
    rbt='reboot'

mcd() {
    mkdir -pv $1
    cd $1
}
maketar() { tar cvzf "${1%%/}.tar.gz"  "${1%%/}/"; }
makezip() { zip -r "${1%%/}.zip" "$1" ; }
